server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location /assets/ {
    try_files $uri =404;
    add_header Cache-Control "public, max-age=31536000, immutable";
  }

  location /api/rss/spektrum {
    proxy_pass https://www.spektrum.de/alias/rss/spektrum-de-rss-feed/996406;
    proxy_ssl_server_name on;
  }

  location /api/rss/geo {
    proxy_pass https://www.geo.de/feed/rss/geo/;
    proxy_ssl_server_name on;
  }

  location /api/rss/zeit {
    proxy_pass https://newsfeed.zeit.de/index;
    proxy_ssl_server_name on;
  }

  location /api/rss/sz {
    proxy_pass https://rss.sueddeutsche.de/rss/Topthemen;
    proxy_ssl_server_name on;
  }

  location /api/rss/spiegel {
    proxy_pass https://www.spiegel.de/schlagzeilen/index.rss;
    proxy_ssl_server_name on;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
